Titan\KillerCrudBundle\Entity\Contract:
    properties:
        target: 
            - NotBlank: ~
        address:
            - NotBlank: ~
            - Url: ~
        reward:
            - NotBlank: ~
            